# Implementation_Of_Statistics_Sales_Data

In [1]:
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.offline as pyo

pyo.init_notebook_mode(connected=True)

In [2]:
sales_data = pd.read_excel("C:\Study\Data Science\Datasets\Sales Data.xlsx")

In [3]:
sales_data.head()

Country     Product  Units Sold  Manufacturing Price  Sale Price  \
0           Japan  Kensington        1372                    3          20   
1           India  Kensington        2762                    3          20   
2  United Kingdom  Kensington        1464                    3          15   
3           India  Kensington         719                    3          15   
4          Brazil  Kensington        3576                    3          15   

   Gross Sales  Discounts    Sales     COGS   Profit       Date Month Name  \
0        27440        0.0  27440.0  16185.0  11255.0 2019-01-01    January   
1        55240        0.0  55240.0  13210.0  42030.0 2019-01-01    January   
2        21960        0.0  21960.0  21780.0    180.0 2019-06-01       June   
3        10785        0.0  10785.0   8880.0   1905.0 2019-06-01       June   
4        53640        0.0  53640.0  24700.0  28940.0 2019-06-01       June   

   Year  
0  2019  
1  2019  
2  2019  
3  2019  
4  2019

In [4]:
sales_data.describe()

Units Sold  Manufacturing Price  Sale Price   Gross Sales  \
count   700.000000           700.000000  700.000000  7.000000e+02   
mean   2380.135714            96.477143  118.428571  2.835507e+05   
min     213.000000             3.000000    7.000000  2.580000e+03   
25%    1335.750000             5.000000   12.000000  2.442000e+04   
50%    2376.000000            10.000000   20.000000  5.515250e+04   
75%    3405.250000           250.000000  300.000000  4.530375e+05   
max    4492.000000           260.000000  350.000000  1.547700e+06   
std    1199.821345           108.602612  136.775515  3.871174e+05   

           Discounts         Sales           COGS        Profit  \
count     700.000000  7.000000e+02     700.000000  7.000000e+02   
mean    13150.354629  2.704004e+05  145475.211429  1.249252e+05   
min         0.000000  8.812500e+02     918.000000 -7.240720e+05   
25%       800.320000  2.308707e+04    7490.000000  2.267505e+03   
50%      2585.250000  5.237088e+04   22506.250000  2.522916e+04   
75%     15956.343750  4.324050e+05  245607.500000  9.789762e+04   
max    149677.500000  1.547700e+06  950625.000000  1.355824e+06   
std     22962.928775  3.754800e+05  203865.506118  2.905832e+05   

                      Date         Year  
count                  700   700.000000  
mean   2019-04-28 21:36:00  2018.750000  
min    2018-09-01 00:00:00  2018.000000  
25%    2018-12-24 06:00:00  2018.750000  
50%    2019-05-16 12:00:00  2019.000000  
75%    2019-09-08 12:00:00  2019.000000  
max    2019-12-01 00:00:00  2019.000000  
std                    NaN     0.433322

In [5]:
sales_data['Country'].unique()

array(['Japan', 'India', 'United Kingdom', 'Brazil',
       'United States of America'], dtype=object)

In [6]:
sales_data['Product'].unique()

array(['Kensington', 'Royal Oak', 'Vermont', 'Burlington', 'Mandarin',
       'Luxe'], dtype=object)

In [7]:
sales_data['Year'].unique()

array([2019, 2018], dtype=int64)

In [8]:
sales_data['Manufacturing Price'].unique()

array([  3,   5,  10, 120, 250, 260], dtype=int64)

In [9]:
sales_data['Sale Price'].unique()

array([ 20,  15, 350,  12, 125, 300,   7], dtype=int64)

In [10]:
sales_data['Sale Price'].mean()

118.42857142857143

In [11]:
sales_data['Sale Price'].median()

20.0

Mean > median there is a outlier in the data

In [12]:
sales_data['Sale Price'].mode()

0      7
1     12
2     15
3     20
4    125
5    300
6    350
Name: Sale Price, dtype: int64

# Sales Performance Analysis:

## Total sales by country, product, month, or year.

In [13]:

fig = px.bar(sales_data, x='Country', y='Sales', title='Total Sales by Country')

fig.show()

In [14]:
fig = px.bar(sales_data, x='Product', y='Sales', title='Total Sales by Product')

fig.show()

In [15]:
fig = px.bar(sales_data, x='Month Name', y='Sales', title='Total Sales by Month')

fig.show()

In [16]:
fig = px.bar(sales_data, x='Year', y='Sales', title='Total Sales by Year')
fig.show()

## Average sale price per product or country.

In [17]:
sales_data['Average Sale Price'] = sales_data['Sale Price']

fig = px.bar(sales_data, x='Country', y='Average Sale Price', title='Average Sale Price per Country')

fig.show()

In [18]:
fig = px.bar(sales_data, x='Product', y='Average Sale Price', title='Average Sale Price per Product')

fig.show()

## Trend analysis of sales over time (monthly, quarterly, annually).

In [19]:
sales_data['Date'] = pd.to_datetime(sales_data['Year'].astype(str) + '-' + sales_data['Month Name'], format='%Y-%B')

monthly_sales = sales_data.groupby('Date')['Sales'].sum().reset_index()

monthly_sales['Quarter'] = monthly_sales['Date'].dt.to_period('Q')
quarterly_sales = monthly_sales.groupby('Quarter')['Sales'].sum().reset_index()

monthly_sales['Year'] = monthly_sales['Date'].dt.year
annual_sales = monthly_sales.groupby('Year')['Sales'].sum().reset_index()

quarterly_sales['Quarter'] = quarterly_sales['Quarter'].astype(str)


In [20]:
fig1 = px.line(monthly_sales, x='Date', y='Sales', title='Monthly Sales Trend')
fig1.show()

In [21]:
fig2 = px.line(quarterly_sales, x='Quarter', y='Sales', title='Quarterly Sales Trend')
fig2.show()

In [22]:
fig3 = px.line(annual_sales, x='Year', y='Sales', title='Annual Sales Trend')
fig3.show()

# Profit Analysis:

In [23]:
# Group the data by Date and sum the Profit
monthly_profit = sales_data.groupby('Date')['Profit'].sum().reset_index()

# Calculate quarterly and annual profit
monthly_profit['Quarter'] = monthly_profit['Date'].dt.to_period('Q')
quarterly_profit = monthly_profit.groupby('Quarter')['Profit'].sum().reset_index()

monthly_profit['Year'] = monthly_profit['Date'].dt.year
annual_profit = monthly_profit.groupby('Year')['Profit'].sum().reset_index()

# Convert the 'Quarter' column to a string
quarterly_profit['Quarter'] = quarterly_profit['Quarter'].astype(str)


## Total profit by country, product, month, or year.

In [24]:
fig1 = px.bar(sales_data, x='Country', y='Profit', title='Total Profit by Country')
fig1.show()

In [25]:
fig2 = px.bar(sales_data, x='Product', y='Profit', title='Total Profit by Product')
fig2.show()

In [26]:
fig3 = px.bar(sales_data, x='Month Name', y='Profit', title='Total Profit by Month')
fig3.show()

In [27]:
fig4 = px.bar(sales_data, x='Year', y='Profit', title='Total Profit by Year')
fig4.show()

## Profit margin per product or country.

In [28]:
sales_data['Profit Margin'] = (sales_data['Profit'] / sales_data['Gross Sales']) * 100
fig1 = px.bar(sales_data, x='Product', y='Profit Margin', title='Profit Margin per Product')
fig1.show()

In [29]:
fig2 = px.bar(sales_data, x='Country', y='Profit Margin', title='Profit Margin per Country')
fig2.show()

## Comparison of profits against sales to determine profitability.

In [30]:
fig1 = px.scatter(sales_data, x='Gross Sales', y='Profit', color='Product',
                  title='Profit vs. Sales (Per Product)')
fig1.show()

In [31]:
fig2 = px.scatter(sales_data, x='Gross Sales', y='Profit', color='Country',
                  title='Profit vs. Sales (Per Country)')
fig2.show()

# Market Analysis

## Market share analysis by country or region.

In [32]:
country_sales = sales_data.groupby('Country')['Units Sold'].sum().reset_index()

total_sales = country_sales['Units Sold'].sum()
country_sales['Market Share'] = (country_sales['Units Sold'] / total_sales) * 100

fig = px.pie(country_sales, names='Country', values='Market Share',
             title='Market Share by Country')

fig.show()

## Identification of growth markets vs. markets with declining sales.

In [33]:
sales_data['Date'] = pd.to_datetime(sales_data['Year'].astype(str) + '-' + sales_data['Month Name'], format='%Y-%B')

country_sales = sales_data.groupby(['Country', 'Date'])['Sales'].sum().reset_index()

fig = px.line(country_sales, x='Date', y='Sales', color='Country',
              title='Sales Trends by Country')

fig.show()

## Analysis of sales distribution across different markets.

In [34]:
country_sales = sales_data.groupby('Country')['Units Sold'].sum().reset_index()

total_sales = country_sales['Units Sold'].sum()
country_sales['Sales Percentage'] = (country_sales['Units Sold'] / total_sales) * 100

fig = px.bar(country_sales, x='Country', y='Sales Percentage', title='Sales Distribution by Market')

fig.show()

# Discount Impact Analysis

## Impact of discounts on sales volume and profit.

In [35]:
sales_data['Discounted Sales'] = sales_data['Gross Sales'] * (1 - sales_data['Discounts'])
sales_data['Discounted Profit'] = sales_data['Discounted Sales'] - sales_data['COGS']


fig = px.scatter(sales_data, x='Discounts', y=['Discounted Sales', 'Discounted Profit'],
                 labels={'variable': 'Metrics'},
                 title='Impact of Discounts on Sales Volume and Profit')

fig.show()


## Correlation between discount levels and sales/profit increases.

In [36]:
# Calculate the increase in Sales and Profit due to discounts
sales_data['Increase in Sales'] = sales_data['Discounted Sales'] - sales_data['Sales']
sales_data['Increase in Profit'] = sales_data['Discounted Profit'] - sales_data['Profit']

# Calculate the correlation coefficients
correlation_sales = np.corrcoef(sales_data['Discounts'], sales_data['Increase in Sales'])[0, 1]
correlation_profit = np.corrcoef(sales_data['Discounts'], sales_data['Increase in Profit'])[0, 1]

fig = px.scatter(sales_data, x='Discounts', y=['Increase in Sales', 'Increase in Profit'],
                 labels={'variable': 'Metrics'},
                 title=f'Correlation between Discounts and Sales/Profit Increases <br>'
                       f'Correlation with Sales: {correlation_sales:.2f}, '
                       f'Correlation with Profit: {correlation_profit:.2f}')

fig.show()

## Effectiveness of discount strategies over time.

In [37]:
sales_data['Discounted Sales'] = sales_data['Gross Sales'] * (1 - sales_data['Discounts'])
sales_data['Discounted Profit'] = sales_data['Discounted Sales'] - sales_data['COGS']

fig = px.line(sales_data, x='Month Name', y=['Discounted Sales', 'Discounted Profit'],
              labels={'variable': 'Metrics'},
              title='Effectiveness of Discount Strategies Over Time')

fig.show()

# Cost Analysis:

## Comparison of COGS (Cost of Goods Sold) with sales and profits.

In [38]:
fig = px.bar(sales_data, x='Country', y=['COGS', 'Sales', 'Profit'],
             labels={'variable': 'Metrics'},
             title='Comparison of COGS, Sales, and Profit by Country')

fig.show()

## Identification of products with high manufacturing costs impacting profits.

In [39]:
fig = px.bar(sales_data, x='Product', y=['Manufacturing Price', 'Profit'],
             labels={'variable': 'Metrics'},
             title='Comparison of Manufacturing Price and Profit by Product')

fig.show()

## Trends in COGS over time.


In [40]:
fig = px.line(sales_data, x='Month Name', y='COGS', labels={'COGS': 'Cost of Goods Sold'},
              title='Trends in Cost of Goods Sold (COGS) Over Time')

fig.show()