<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Module-5:Introduction-to-NumPy" data-toc-modified-id="Module-5:Introduction-to-NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Module 5:Introduction to NumPy</a></span><ul class="toc-item"><li><span><a href="#Convertthegivenlistintoa-numpy-array--and-replace-the-odd-elementswith-2.Lst=[[1,2,3],-[4,5,6],-[7,8,9]]" data-toc-modified-id="Convertthegivenlistintoa-numpy-array--and-replace-the-odd-elementswith-2.Lst=[[1,2,3],-[4,5,6],-[7,8,9]]-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Convertthegivenlistintoa numpy array  and replace the odd elementswith-2.Lst=[[1,2,3], [4,5,6], [7,8,9]]</a></span></li><li><span><a href="#In-the-numpyarray-given-below-print-all-the-elements-ranging-from-8-to-15.arr-=-[1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]" data-toc-modified-id="In-the-numpyarray-given-below-print-all-the-elements-ranging-from-8-to-15.arr-=-[1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>In the numpyarray given below print all the elements ranging from 8 to 15.arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]</a></span></li><li><span><a href="#Create-a-3*3-narray-thatincludes-numbersfrom-1-to-9-and-swap-columns1-and2." data-toc-modified-id="Create-a-3*3-narray-thatincludes-numbersfrom-1-to-9-and-swap-columns1-and2.-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Create a 3*3 narray thatincludes numbersfrom 1 to 9 and swap columns1 and2.</a></span></li><li><span><a href="#In-the-given-numpyarray-replace-the-NaN-values-with-the-average-of-columnsarr=-np.array([[1.3,-2.5,-3.6,-np.nan],-[2.6,-3.3,-np.nan,-5.5],-[2.1,-3.2,-5.4,-6.5]])" data-toc-modified-id="In-the-given-numpyarray-replace-the-NaN-values-with-the-average-of-columnsarr=-np.array([[1.3,-2.5,-3.6,-np.nan],-[2.6,-3.3,-np.nan,-5.5],-[2.1,-3.2,-5.4,-6.5]])-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>In the given numpyarray replace the NaN values with the average of columnsarr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])</a></span></li><li><span><a href="#For-the-numpyarray-given-below-perform-the-following-operation:i.Convert-the-numpyarray-into-a-numpymatrixii.Sort-the-values-in-a-matrixarr-=-[[2,4,6],[1,3,5]]" data-toc-modified-id="For-the-numpyarray-given-below-perform-the-following-operation:i.Convert-the-numpyarray-into-a-numpymatrixii.Sort-the-values-in-a-matrixarr-=-[[2,4,6],[1,3,5]]-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>For the numpyarray given below perform the following operation:i.Convert the numpyarray into a numpymatrixii.Sort the values in a matrixarr = [[2,4,6],[1,3,5]]</a></span></li></ul></li></ul></div>

# Module 5:Introduction to NumPy

## Convertthegivenlistintoa numpy array  and replace the odd elementswith-2.Lst=[[1,2,3], [4,5,6], [7,8,9]]

In [1]:
import numpy as np

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(lst)  # Convert the list to a NumPy array

# Replace the odd elements with -2
arr[arr % 2 == 1] = -2

print(arr)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


## In the numpyarray given below print all the elements ranging from 8 to 15.arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]



In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7])

# Use boolean indexing to select elements in the specified range
selected_elements = arr[(arr >= 8) & (arr <= 15)]

# Print the selected elements
print(selected_elements)


[ 8  9 10 12]


## Create a 3*3 narray thatincludes numbersfrom 1 to 9 and swap columns1 and2.

In [7]:
import numpy as np

# Create a 3x3 NumPy array with numbers from 1 to 9
original_array = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

# Swap columns 1 and 2
swapped_array = original_array[:, [1, 0, 2]]

# Print the swapped array
print(swapped_array)


[[2 1 3]
 [5 4 6]
 [8 7 9]]


## In the given numpyarray replace the NaN values with the average of columnsarr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])

In [8]:
import numpy as np

arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

# Calculate the column-wise means, ignoring NaN values
column_means = np.nanmean(arr, axis=0)

# Find the indices of NaN values in the array
nan_indices = np.isnan(arr)

# Replace NaN values with the respective column means
arr[nan_indices] = np.take(column_means, np.where(nan_indices)[1])

# Print the array with NaN values replaced by column means
print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


## For the numpyarray given below perform the following operation:i.Convert the numpyarray into a numpymatrixii.Sort the values in a matrixarr = [[2,4,6],[1,3,5]]

In [10]:
import numpy as np

arr = np.array([[2, 4, 6], [1, 3, 5]])

# Convert the NumPy array into a NumPy matrix
matrix = np.matrix(arr)

# Sort the values in the matrix
sorted_matrix = np.sort(matrix, axis=None)

# Print the sorted matrix
print(sorted_matrix)


[[1 2 3 4 5 6]]
