<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [80]:
import numpy as np
import pandas as pd

In [2]:
l=[1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
arr1=np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
mat = np.matrix(l)

In [16]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [18]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
a = arr

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0]=100

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [26]:
b = np.copy(arr) #shallow copy

In [27]:
b

array([100,   2,   3,   4,   5])

In [28]:
arr[0]=101

In [29]:
arr

array([101,   2,   3,   4,   5])

In [30]:
b

array([100,   2,   3,   4,   5])

In [33]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [38]:
iterable = (i*i for i in range(5))

In [39]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [41]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [42]:
arr

array([101,   2,   3,   4,   5])

In [43]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [44]:
arr.ndim

1

In [47]:
arr1.ndim

2

In [48]:
arr.size

5

In [49]:
arr1.size

10

In [50]:
arr.shape

(5,)

In [51]:
arr1.shape

(2, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
arr1.dtype

dtype('int32')

In [54]:
list(range(5))

[0, 1, 2, 3, 4]

In [55]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
list(0.4,10.4)

TypeError: list expected at most 1 argument, got 2

In [57]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [58]:
np.arange(0.4,10.4,0.5)

array([0.4, 0.9, 1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4,
       6.9, 7.4, 7.9, 8.4, 8.9, 9.4, 9.9])

In [59]:
l = list(np.arange(0.4,10.4,0.5))

In [60]:
l

[0.4,
 0.9,
 1.4,
 1.9,
 2.4,
 2.9,
 3.4,
 3.9,
 4.4,
 4.9,
 5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9]

In [62]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [63]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [64]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [73]:
arr=np.ones((3,4))

In [74]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [75]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [76]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
arr1 =np.eye(5)

In [78]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [83]:
np.random.rand(2,3)

array([[0.20013184, 0.58815569, 0.23040672],
       [0.36737005, 0.49905235, 0.4676066 ]])

In [84]:
np.random.randn(2,3)

array([[-0.82230598, -0.45093016,  1.24990161],
       [ 0.68952939, -2.06053749, -0.41655663]])

In [86]:
arr2=np.random.randint(1,5,(3,4))

In [87]:
arr2.size

12

In [88]:
arr2.shape

(3, 4)

In [89]:
arr2.reshape(6,2)

array([[2, 3],
       [1, 2],
       [3, 3],
       [1, 1],
       [4, 3],
       [4, 2]])

In [91]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [92]:
arr2.reshape(4,3)

array([[2, 3, 1],
       [2, 3, 3],
       [1, 1, 4],
       [3, 4, 2]])

In [93]:
arr2.reshape(4,-1)

array([[2, 3, 1],
       [2, 3, 3],
       [1, 1, 4],
       [3, 4, 2]])

In [94]:
arr2.reshape(4,-1456456)

array([[2, 3, 1],
       [2, 3, 3],
       [1, 1, 4],
       [3, 4, 2]])

In [95]:
arr2.reshape(2,2,3)

array([[[2, 3, 1],
        [2, 3, 3]],

       [[1, 1, 4],
        [3, 4, 2]]])

In [99]:
arr1=np.random.randint(1,10,(5,6))

In [100]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [101]:
arr1[arr1>8]

array([9])

In [102]:
arr1

array([[5, 8, 6, 8, 2, 6],
       [6, 8, 3, 5, 4, 6],
       [6, 2, 8, 4, 4, 8],
       [8, 7, 6, 6, 3, 6],
       [7, 6, 5, 6, 9, 5]])

In [103]:
arr1[0,0:2]

array([5, 8])

In [104]:
arr1[0,[0,1]]

array([5, 8])

In [106]:
arr1[2:4,[2,3]]

array([[8, 4],
       [6, 6]])

In [109]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [110]:
arr1

array([[2, 2, 1],
       [2, 1, 1],
       [1, 1, 2]])

In [111]:
arr2

array([[2, 2, 1],
       [2, 2, 1],
       [2, 2, 2]])

In [112]:
arr1+arr2

array([[4, 4, 2],
       [4, 3, 2],
       [3, 3, 4]])

In [113]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0, -1,  0],
       [-1, -1,  0]])

In [115]:
arr1*arr2 # index multiplication

array([[4, 4, 1],
       [4, 2, 1],
       [2, 2, 4]])

In [117]:
arr1@arr2

array([[10, 10,  6],
       [ 8,  8,  5],
       [ 8,  8,  6]])

In [118]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 0.5, 1. ],
       [0.5, 0.5, 1. ]])

In [119]:
arr1/0

C:\Users\thang\AppData\Local\Temp\ipykernel_9112\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [120]:
# Numpy Broadcasting

In [121]:
arr = np.zeros((3,4))

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [124]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [125]:
a = np.array([1,2,3,4])

In [126]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [133]:
b = np.array([[3,4,5]])

In [135]:
arr1=arr+b.T

In [136]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [137]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [138]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [139]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [140]:
np.min(arr1)

3.0

In [141]:
np.max(arr1)

5.0

In [143]:
n = np.random.randint(1,10,(4,4))

In [144]:
n

array([[8, 3, 9, 2],
       [9, 4, 4, 7],
       [9, 9, 6, 4],
       [1, 6, 1, 7]])

In [145]:
n.reshape(8,2)

array([[8, 3],
       [9, 2],
       [9, 4],
       [4, 7],
       [9, 9],
       [6, 4],
       [1, 6],
       [1, 7]])

In [146]:
n.T

array([[8, 9, 9, 1],
       [3, 4, 9, 6],
       [9, 4, 6, 1],
       [2, 7, 4, 7]])

In [149]:
n.flatten()

array([8, 3, 9, 2, 9, 4, 4, 7, 9, 9, 6, 4, 1, 6, 1, 7])

In [150]:
np.expand_dims(n)

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [151]:
np.expand_dims(n,axis=1)

array([[[8, 3, 9, 2]],

       [[9, 4, 4, 7]],

       [[9, 9, 6, 4]],

       [[1, 6, 1, 7]]])

In [153]:
np.expand_dims(n,axis=0)

array([[[8, 3, 9, 2],
        [9, 4, 4, 7],
        [9, 9, 6, 4],
        [1, 6, 1, 7]]])

In [154]:
data = np.array([[1],[2],[3]])

In [155]:
data

array([[1],
       [2],
       [3]])

In [156]:
np.squeeze(data)

array([1, 2, 3])

In [157]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [158]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [159]:
np.roll(data,2)  

array([[2],
       [3],
       [1]])

In [161]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [163]:
arr1= np.random.randint(1,10,(3,4))
arr2= np.random.randint(1,10,(3,4))

In [164]:
arr1

array([[1, 5, 7, 7],
       [3, 3, 5, 3],
       [1, 9, 6, 3]])

In [165]:
arr2

array([[2, 7, 3, 4],
       [4, 2, 8, 2],
       [9, 2, 3, 4]])

In [166]:
arr1+arr2

array([[ 3, 12, 10, 11],
       [ 7,  5, 13,  5],
       [10, 11,  9,  7]])

In [167]:
arr1*arr2

array([[ 2, 35, 21, 28],
       [12,  6, 40,  6],
       [ 9, 18, 18, 12]])

In [169]:
arr1/arr2

array([[0.5       , 0.71428571, 2.33333333, 1.75      ],
       [0.75      , 1.5       , 0.625     , 1.5       ],
       [0.11111111, 4.5       , 2.        , 0.75      ]])

In [171]:
arr1-arr2

array([[-1, -2,  4,  3],
       [-1,  1, -3,  1],
       [-8,  7,  3, -1]])

In [172]:
arr1**arr2

array([[     1,  78125,    343,   2401],
       [    81,      9, 390625,      9],
       [     1,     81,    216,     81]])

In [173]:
~arr1

array([[ -2,  -6,  -8,  -8],
       [ -4,  -4,  -6,  -4],
       [ -2, -10,  -7,  -4]])

In [174]:
arr1>arr2

array([[False, False,  True,  True],
       [False,  True, False,  True],
       [False,  True,  True, False]])

In [175]:
arr=np.array(["praddep","Kumar"])

In [176]:
np.char.upper(arr)

array(['PRADDEP', 'KUMAR'], dtype='<U7')

In [177]:
np.char.capitalize(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [178]:
np.char.title(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [179]:
arr1

array([[1, 5, 7, 7],
       [3, 3, 5, 3],
       [1, 9, 6, 3]])

In [180]:
np.sin(arr1)

array([[ 0.84147098, -0.95892427,  0.6569866 ,  0.6569866 ],
       [ 0.14112001,  0.14112001, -0.95892427,  0.14112001],
       [ 0.84147098,  0.41211849, -0.2794155 ,  0.14112001]])

In [181]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219,  0.75390225,  0.75390225],
       [-0.9899925 , -0.9899925 ,  0.28366219, -0.9899925 ],
       [ 0.54030231, -0.91113026,  0.96017029, -0.9899925 ]])

In [182]:
np.tan(arr1)

array([[ 1.55740772, -3.38051501,  0.87144798,  0.87144798],
       [-0.14254654, -0.14254654, -3.38051501, -0.14254654],
       [ 1.55740772, -0.45231566, -0.29100619, -0.14254654]])

In [183]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.84509804, 0.84509804],
       [0.47712125, 0.47712125, 0.69897   , 0.47712125],
       [0.        , 0.95424251, 0.77815125, 0.47712125]])

In [184]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 1.09663316e+03, 1.09663316e+03],
       [2.00855369e+01, 2.00855369e+01, 1.48413159e+02, 2.00855369e+01],
       [2.71828183e+00, 8.10308393e+03, 4.03428793e+02, 2.00855369e+01]])

In [185]:
np.power(arr1,2)

array([[ 1, 25, 49, 49],
       [ 9,  9, 25,  9],
       [ 1, 81, 36,  9]], dtype=int32)

In [186]:
np.mean(arr1)

4.416666666666667

In [187]:
np.median(arr1)

4.0

In [189]:
np.std(arr1)

2.396467307424734

In [190]:
np.var(arr1)

5.7430555555555545

In [191]:
np.min(arr1)

1

In [192]:
np.max(arr1)

9

In [193]:
arr1

array([[1, 5, 7, 7],
       [3, 3, 5, 3],
       [1, 9, 6, 3]])

In [194]:
arr2

array([[2, 7, 3, 4],
       [4, 2, 8, 2],
       [9, 2, 3, 4]])

In [196]:
arr1-arr2

array([[-1, -2,  4,  3],
       [-1,  1, -3,  1],
       [-8,  7,  3, -1]])

In [197]:
np.subtract(arr1,arr2)

array([[-1, -2,  4,  3],
       [-1,  1, -3,  1],
       [-8,  7,  3, -1]])

In [199]:
np.multiply(arr1,arr2)

array([[ 2, 35, 21, 28],
       [12,  6, 40,  6],
       [ 9, 18, 18, 12]])

In [200]:
np.mod(arr1,arr2)

array([[1, 5, 1, 3],
       [3, 1, 5, 1],
       [1, 1, 0, 3]])

In [201]:
np.power(arr1,arr2)

array([[     1,  78125,    343,   2401],
       [    81,      9, 390625,      9],
       [     1,     81,    216,     81]])

In [204]:
np.sqrt(arr1)

array([[1.        , 2.23606798, 2.64575131, 2.64575131],
       [1.73205081, 1.73205081, 2.23606798, 1.73205081],
       [1.        , 3.        , 2.44948974, 1.73205081]])

In [205]:
np.mean(arr1)

4.416666666666667

In [206]:
np.median(arr1)

4.0

In [207]:
np.std(arr1)

2.396467307424734

In [208]:
np.var(arr1)

5.7430555555555545

In [212]:
a=np.array([20,3,40,5,6])

In [213]:
np.sort(a)

array([ 3,  5,  6, 20, 40])

In [217]:
np.searchsorted(a,6)

2

In [218]:
np.searchsorted(a,60)

5

In [219]:
arr1=np.array([0,2,6,4,8888,8654641,1,0])

In [220]:
np.count_nonzero(arr1)

6

In [222]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [225]:
np.extract(arr1>50,arr1)

array([   8888, 8654641])

In [226]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [228]:
arr.byteswap()

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [229]:
arr

array(['praddep', 'Kumar'], dtype='<U7')

In [231]:
arr.byteswap(True)

array(['praddep', 'Kumar'], dtype='<U7')

In [232]:
a

array([20,  3, 40,  5,  6])

In [233]:
d=np.copy(a)

In [234]:
d

array([20,  3, 40,  5,  6])

In [235]:
d = arr.view()

In [236]:
d

array(['praddep', 'Kumar'], dtype='<U7')

In [237]:
d[0]=234

In [238]:
d

array(['234', 'Kumar'], dtype='<U7')

In [239]:
arr

array(['234', 'Kumar'], dtype='<U7')

In [240]:
import numpy.matlib as nm

In [241]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [243]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [244]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [245]:
# Linear Algebra

In [246]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [255]:
arr1=np.random.randint([[2,3],[4,5]])

In [256]:
arr2=np.random.randint([[5,3],[2,5]])

In [257]:
arr1

array([[0, 2],
       [2, 1]])

In [258]:
arr2

array([[0, 0],
       [1, 4]])

In [261]:
np.dot(arr1,arr2)

array([[2, 8],
       [1, 4]])

In [260]:
arr1@arr2

array([[2, 8],
       [1, 4]])