<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np
import pandas as pd

C:\Users\USER\AppData\Local\Temp\ipykernel_11496\1662815981.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
l=[1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1=np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

In [7]:
arr.ndim

1

In [8]:
arr1.ndim

2

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [10]:
mat = np.matrix(l)

In [11]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [12]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
a = arr

In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr[0]=100

In [18]:
arr

array([100,   2,   3,   4,   5])

In [19]:
a

array([100,   2,   3,   4,   5])

In [20]:
b = np.copy(arr) #shallow copy

In [21]:
b

array([100,   2,   3,   4,   5])

In [22]:
arr[0]=101

In [23]:
arr

array([101,   2,   3,   4,   5])

In [24]:
b

array([100,   2,   3,   4,   5])

In [25]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [28]:
iterable = (i*i for i in range(5))

In [29]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [30]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [31]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [32]:
arr

array([101,   2,   3,   4,   5])

In [33]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [34]:
arr.ndim

1

In [35]:
arr1.ndim

2

In [36]:
arr.size

5

In [37]:
arr1.size

10

In [38]:
arr.shape

(5,)

In [39]:
arr1.shape

(2, 5)

In [40]:
arr.dtype

dtype('int32')

In [41]:
arr1.dtype

dtype('int32')

In [42]:
list(range(5))

[0, 1, 2, 3, 4]

In [43]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [44]:
list(0.4,10.4)

TypeError: list expected at most 1 argument, got 2

In [45]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [46]:
np.arange(0.4,10.4,0.5)

array([0.4, 0.9, 1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4,
       6.9, 7.4, 7.9, 8.4, 8.9, 9.4, 9.9])

In [47]:
l = list(np.arange(0.4,10.4,0.5))

In [48]:
l

[0.4,
 0.9,
 1.4,
 1.9,
 2.4,
 2.9,
 3.4,
 3.9,
 4.4,
 4.9,
 5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9]

In [49]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [50]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [51]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [56]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [57]:
arr=np.ones((3,4))

In [58]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [59]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [60]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr1 =np.eye(5)

In [62]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [64]:
np.random.rand(2,3)

array([[0.63487245, 0.4635976 , 0.15850488],
       [0.82467317, 0.5457064 , 0.97135042]])

In [65]:
np.random.randn(2,3)

array([[-0.96505307, -1.13902583, -0.21050554],
       [ 1.10158232, -1.33864141,  1.45485189]])

In [66]:
arr2=np.random.randint(1,5,(3,4))

In [67]:
arr2.size

12

In [68]:
arr2.shape

(3, 4)

In [69]:
arr2.reshape(6,2)

array([[3, 3],
       [1, 4],
       [2, 2],
       [2, 3],
       [4, 2],
       [3, 4]])

In [70]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [ ]:
arr2.reshape(4,3)

In [71]:
arr2.reshape(4,-1)

array([[3, 3, 1],
       [4, 2, 2],
       [2, 3, 4],
       [2, 3, 4]])

In [72]:
arr2.reshape(4,-1456456)

array([[3, 3, 1],
       [4, 2, 2],
       [2, 3, 4],
       [2, 3, 4]])

In [73]:
arr2.reshape(2,2,3)

array([[[3, 3, 1],
        [4, 2, 2]],

       [[2, 3, 4],
        [2, 3, 4]]])

In [74]:
arr1=np.random.randint(1,10,(5,6))

In [75]:
arr1>8

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [76]:
arr1[arr1>8]

array([9])

In [77]:
arr1

array([[2, 7, 2, 4, 8, 9],
       [2, 5, 3, 5, 1, 7],
       [1, 3, 4, 3, 3, 6],
       [4, 7, 3, 6, 1, 1],
       [1, 7, 7, 6, 2, 5]])

In [78]:
arr1[0,0:2]

array([2, 7])

In [79]:
arr1[0,[0,1]]

array([2, 7])

In [80]:
arr1[2:4,[2,3]]

array([[4, 3],
       [3, 6]])

In [81]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [82]:
arr1

array([[1, 2, 2],
       [1, 1, 1],
       [2, 2, 1]])

In [83]:
arr2

array([[2, 2, 2],
       [2, 1, 2],
       [2, 1, 2]])

In [84]:
arr1+arr2

array([[3, 4, 4],
       [3, 2, 3],
       [4, 3, 3]])

In [85]:
arr1-arr2

array([[-1,  0,  0],
       [-1,  0, -1],
       [ 0,  1, -1]])

In [86]:
arr1*arr2 # index multiplication

array([[2, 4, 4],
       [2, 1, 2],
       [4, 2, 2]])

In [87]:
arr1@arr2

array([[10,  6, 10],
       [ 6,  4,  6],
       [10,  7, 10]])

In [88]:
arr1/arr2

array([[0.5, 1. , 1. ],
       [0.5, 1. , 0.5],
       [1. , 2. , 0.5]])

In [89]:
arr1/0

C:\Users\USER\AppData\Local\Temp\ipykernel_11496\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [90]:
# Numpy Broadcasting

In [91]:
arr = np.zeros((3,4))

In [92]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [94]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [95]:
a = np.array([1,2,3,4])

In [96]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [97]:
b = np.array([[3,4,5]])

In [98]:
arr1=arr+b.T

In [99]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [100]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [101]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [102]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [103]:
np.min(arr1)

3.0

In [104]:
np.max(arr1)

5.0

In [105]:
n = np.random.randint(1,10,(4,4))

In [106]:
n

array([[6, 4, 2, 5],
       [9, 4, 5, 7],
       [6, 5, 3, 6],
       [5, 7, 7, 4]])

In [107]:
n.reshape(8,2)

array([[6, 4],
       [2, 5],
       [9, 4],
       [5, 7],
       [6, 5],
       [3, 6],
       [5, 7],
       [7, 4]])

In [108]:
n.T

array([[6, 9, 6, 5],
       [4, 4, 5, 7],
       [2, 5, 3, 7],
       [5, 7, 6, 4]])

In [109]:
n.flatten()

array([6, 4, 2, 5, 9, 4, 5, 7, 6, 5, 3, 6, 5, 7, 7, 4])

In [110]:
np.expand_dims(n)

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [111]:
np.expand_dims(n,axis=1)

array([[[6, 4, 2, 5]],

       [[9, 4, 5, 7]],

       [[6, 5, 3, 6]],

       [[5, 7, 7, 4]]])

In [112]:
np.expand_dims(n,axis=0)

array([[[6, 4, 2, 5],
        [9, 4, 5, 7],
        [6, 5, 3, 6],
        [5, 7, 7, 4]]])

In [113]:
data = np.array([[1],[2],[3]])

In [114]:
data

array([[1],
       [2],
       [3]])

In [115]:
np.squeeze(data)

array([1, 2, 3])

In [116]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [117]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [118]:
np.roll(data,2)  

array([[2],
       [3],
       [1]])

In [119]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [120]:
arr1= np.random.randint(1,10,(3,4))
arr2= np.random.randint(1,10,(3,4))

In [121]:
arr1

array([[8, 4, 1, 1],
       [2, 5, 1, 3],
       [4, 2, 3, 6]])

In [122]:
arr2

array([[3, 5, 7, 7],
       [6, 4, 6, 8],
       [8, 8, 8, 8]])

In [123]:
arr1+arr2

array([[11,  9,  8,  8],
       [ 8,  9,  7, 11],
       [12, 10, 11, 14]])

In [124]:
arr1*arr2

array([[24, 20,  7,  7],
       [12, 20,  6, 24],
       [32, 16, 24, 48]])

In [125]:
arr1/arr2

array([[2.66666667, 0.8       , 0.14285714, 0.14285714],
       [0.33333333, 1.25      , 0.16666667, 0.375     ],
       [0.5       , 0.25      , 0.375     , 0.75      ]])

In [126]:
arr1-arr2

array([[ 5, -1, -6, -6],
       [-4,  1, -5, -5],
       [-4, -6, -5, -2]])

In [127]:
arr1**arr2

array([[    512,    1024,       1,       1],
       [     64,     625,       1,    6561],
       [  65536,     256,    6561, 1679616]])

In [128]:
~arr1

array([[-9, -5, -2, -2],
       [-3, -6, -2, -4],
       [-5, -3, -4, -7]])

In [129]:
arr1>arr2

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [130]:
arr=np.array(["praddep","Kumar"])

In [131]:
np.char.upper(arr)

array(['PRADDEP', 'KUMAR'], dtype='<U7')

In [132]:
np.char.capitalize(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [133]:
np.char.title(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [134]:
arr1

array([[8, 4, 1, 1],
       [2, 5, 1, 3],
       [4, 2, 3, 6]])

In [135]:
np.sin(arr1)

array([[ 0.98935825, -0.7568025 ,  0.84147098,  0.84147098],
       [ 0.90929743, -0.95892427,  0.84147098,  0.14112001],
       [-0.7568025 ,  0.90929743,  0.14112001, -0.2794155 ]])

In [136]:
np.cos(arr1)

array([[-0.14550003, -0.65364362,  0.54030231,  0.54030231],
       [-0.41614684,  0.28366219,  0.54030231, -0.9899925 ],
       [-0.65364362, -0.41614684, -0.9899925 ,  0.96017029]])

In [137]:
np.tan(arr1)

array([[-6.79971146,  1.15782128,  1.55740772,  1.55740772],
       [-2.18503986, -3.38051501,  1.55740772, -0.14254654],
       [ 1.15782128, -2.18503986, -0.14254654, -0.29100619]])

In [138]:
np.log10(arr1)

array([[0.90308999, 0.60205999, 0.        , 0.        ],
       [0.30103   , 0.69897   , 0.        , 0.47712125],
       [0.60205999, 0.30103   , 0.47712125, 0.77815125]])

In [139]:
np.exp(arr1)

array([[2.98095799e+03, 5.45981500e+01, 2.71828183e+00, 2.71828183e+00],
       [7.38905610e+00, 1.48413159e+02, 2.71828183e+00, 2.00855369e+01],
       [5.45981500e+01, 7.38905610e+00, 2.00855369e+01, 4.03428793e+02]])

In [140]:
np.power(arr1,2)

array([[64, 16,  1,  1],
       [ 4, 25,  1,  9],
       [16,  4,  9, 36]], dtype=int32)

In [141]:
np.mean(arr1)

3.3333333333333335

In [142]:
np.median(arr1)

3.0

In [143]:
np.std(arr1)

2.0949675149960894

In [144]:
np.var(arr1)

4.388888888888889

In [145]:
np.min(arr1)

1

In [146]:
np.max(arr1)

8

In [147]:
arr1

array([[8, 4, 1, 1],
       [2, 5, 1, 3],
       [4, 2, 3, 6]])

In [148]:
arr2

array([[3, 5, 7, 7],
       [6, 4, 6, 8],
       [8, 8, 8, 8]])

In [149]:
arr1-arr2

array([[ 5, -1, -6, -6],
       [-4,  1, -5, -5],
       [-4, -6, -5, -2]])

In [150]:
np.subtract(arr1,arr2)

array([[ 5, -1, -6, -6],
       [-4,  1, -5, -5],
       [-4, -6, -5, -2]])

In [151]:
np.multiply(arr1,arr2)

array([[24, 20,  7,  7],
       [12, 20,  6, 24],
       [32, 16, 24, 48]])

In [152]:
np.mod(arr1,arr2)

array([[2, 4, 1, 1],
       [2, 1, 1, 3],
       [4, 2, 3, 6]])

In [153]:
np.power(arr1,arr2)

array([[    512,    1024,       1,       1],
       [     64,     625,       1,    6561],
       [  65536,     256,    6561, 1679616]])

In [154]:
np.sqrt(arr1)

array([[2.82842712, 2.        , 1.        , 1.        ],
       [1.41421356, 2.23606798, 1.        , 1.73205081],
       [2.        , 1.41421356, 1.73205081, 2.44948974]])

In [155]:
np.mean(arr1)

3.3333333333333335

In [156]:
np.median(arr1)

3.0

In [157]:
np.std(arr1)

2.0949675149960894

In [158]:
np.var(arr1)

4.388888888888889

In [159]:
a=np.array([20,3,40,5,6])

In [160]:
np.sort(a)

array([ 3,  5,  6, 20, 40])

In [161]:
np.searchsorted(a,6)

2

In [162]:
np.searchsorted(a,60)

5

In [163]:
arr1=np.array([0,2,6,4,8888,8654641,1,0])

In [164]:
np.count_nonzero(arr1)

6

In [165]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [166]:
np.extract(arr1>50,arr1)

array([   8888, 8654641])

In [167]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [168]:
arr.byteswap()

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [169]:
arr

array(['praddep', 'Kumar'], dtype='<U7')

In [170]:
arr.byteswap(True)

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [171]:
a

array([20,  3, 40,  5,  6])

In [172]:
d=np.copy(a)

In [173]:
d

array([20,  3, 40,  5,  6])

In [174]:
d = arr.view()

In [175]:
d

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [176]:
d[0]=234

In [177]:
d

array(['234', '\U4b000000\U75000000\U6d000000\U61000000\U72000000'],
      dtype='<U7')

In [178]:
arr

array(['234', '\U4b000000\U75000000\U6d000000\U61000000\U72000000'],
      dtype='<U7')

In [179]:
import numpy.matlib as nm

In [180]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [181]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [182]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [183]:
# Linear Algebra

In [184]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [185]:
arr1=np.random.randint([[2,3],[4,5]])

In [186]:
arr2=np.random.randint([[5,3],[2,5]])

In [187]:
arr1

array([[0, 1],
       [3, 2]])

In [188]:
arr2

array([[2, 0],
       [0, 1]])

In [189]:
np.dot(arr1,arr2)

array([[0, 1],
       [6, 2]])

In [190]:
arr1@arr2

array([[0, 1],
       [6, 2]])

In [191]:
a = np.array([1,2,3])

In [192]:
54321
5432
543
54
5

5

In [193]:
for i in range(5,0,-1):
    for j in range(5,5-i,-1):
        print(j,end='')
    print()

54321
5432
543
54
5


In [194]:
Now for the same list give me the frequencies along with unique values.
['1','6','9','3','0','12','11','7','6','11','0','11']

{'1':1, '11':3...}
Sorted by Key.

Also find the "Alphabet" quivalent for each of these numbers considering 
0 as A
25 as Z

SyntaxError: invalid syntax (1411854687.py, line 1)

In [ ]:
# create a fibonacci series.
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_series = fibonacci(n - 1)
        fib_series.append(fib_series[-1] + fib_series[-2])
        return fib_series

n = int(input("Enter the number of Fibonacci numbers to generate: "))
fib_series = fibonacci(n)
print(f"Fibonacci series of length {n}:")
print(fib_series)


In [ ]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Print the unique values and their frequencies
print("Unique Values:", unique_values)
print("Frequencies:", frequencies)


In [ ]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Create a dictionary with unique values as keys and frequencies as values
result_dict = {unique_values[i]: frequencies[i] for i in range(len(unique_values))}

# Sort the dictionary by key in ascending order
sorted_result = dict(sorted(result_dict.items()))

# Print the sorted dictionary
print(sorted_result)


In [ ]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Create a dictionary with unique values as keys and frequencies as values
result_dict = {unique_values[i]: frequencies[i] for i in range(len(unique_values))}

# Sort the dictionary by key in ascending order
sorted_result = dict(sorted(result_dict.items()))

# Define a function to convert numbers to alphabets
def num_to_alphabet(num):
    return chr(ord('A') + int(num))

# Convert the keys to alphabets in the sorted dictionary
alphabet_equivalent = {num_to_alphabet(k): v for k, v in sorted_result.items()}

# Print the sorted dictionary with alphabet equivalents
print(alphabet_equivalent)
