<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
import numpy as np
import pandas as pd

In [3]:
l=[1,2,3,4,5]

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1=np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])

In [8]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [10]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
mat = np.matrix(l)

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [13]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[0]=100

In [19]:
arr

array([100,   2,   3,   4,   5])

In [20]:
a

array([100,   2,   3,   4,   5])

In [21]:
b = np.copy(arr) #shallow copy

In [22]:
b

array([100,   2,   3,   4,   5])

In [23]:
arr[0]=101

In [24]:
arr

array([101,   2,   3,   4,   5])

In [25]:
b

array([100,   2,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [29]:
iterable = (i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('23 45 56',sep=' ')

array([23., 45., 56.])

In [32]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [33]:
arr

array([101,   2,   3,   4,   5])

In [34]:
arr1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [35]:
arr.ndim

1

In [36]:
arr1.ndim

2

In [37]:
arr.size

5

In [38]:
arr1.size

10

In [39]:
arr.shape

(5,)

In [40]:
arr1.shape

(2, 5)

In [41]:
arr.dtype

dtype('int32')

In [42]:
arr1.dtype

dtype('int32')

In [43]:
list(range(5))

[0, 1, 2, 3, 4]

In [44]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
list(0.4,10.4)

TypeError: list expected at most 1 argument, got 2

In [46]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [47]:
np.arange(0.4,10.4,0.5)

array([0.4, 0.9, 1.4, 1.9, 2.4, 2.9, 3.4, 3.9, 4.4, 4.9, 5.4, 5.9, 6.4,
       6.9, 7.4, 7.9, 8.4, 8.9, 9.4, 9.9])

In [48]:
l = list(np.arange(0.4,10.4,0.5))

In [49]:
l

[0.4,
 0.9,
 1.4,
 1.9,
 2.4,
 2.9,
 3.4,
 3.9,
 4.4,
 4.9,
 5.4,
 5.9,
 6.4,
 6.9,
 7.4,
 7.9,
 8.4,
 8.9,
 9.4,
 9.9]

In [50]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [51]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [52]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
arr=np.ones((3,4))

In [59]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [60]:
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
arr1 =np.eye(5)

In [63]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [65]:
np.random.rand(2,3)

array([[0.97061819, 0.28697879, 0.92091414],
       [0.24816884, 0.10673218, 0.25047006]])

In [66]:
np.random.randn(2,3)

array([[ 1.36563261, -1.09583003,  0.01550486],
       [-1.30671867,  0.37061016,  0.01307206]])

In [67]:
arr2=np.random.randint(1,5,(3,4))

In [68]:
arr2.size

12

In [69]:
arr2.shape

(3, 4)

In [70]:
arr2.reshape(6,2)

array([[2, 4],
       [2, 3],
       [1, 1],
       [2, 3],
       [4, 4],
       [3, 3]])

In [71]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [72]:
arr2.reshape(4,3)

array([[2, 4, 2],
       [3, 1, 1],
       [2, 3, 4],
       [4, 3, 3]])

In [73]:
arr2.reshape(4,-1)

array([[2, 4, 2],
       [3, 1, 1],
       [2, 3, 4],
       [4, 3, 3]])

In [74]:
arr2.reshape(4,-1456456)

array([[2, 4, 2],
       [3, 1, 1],
       [2, 3, 4],
       [4, 3, 3]])

In [75]:
arr2.reshape(2,2,3)

array([[[2, 4, 2],
        [3, 1, 1]],

       [[2, 3, 4],
        [4, 3, 3]]])

In [76]:
arr1=np.random.randint(1,10,(5,6))

In [77]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [78]:
arr1[arr1>8]

array([9, 9])

In [79]:
arr1

array([[8, 2, 3, 2, 4, 8],
       [2, 4, 5, 5, 9, 3],
       [6, 8, 9, 2, 2, 4],
       [7, 8, 7, 3, 1, 3],
       [4, 2, 3, 8, 8, 8]])

In [80]:
arr1[0,0:2]

array([8, 2])

In [81]:
arr1[0,[0,1]]

array([8, 2])

In [82]:
arr1[2:4,[2,3]]

array([[9, 2],
       [7, 3]])

In [83]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [84]:
arr1

array([[1, 1, 2],
       [1, 2, 1],
       [1, 1, 1]])

In [85]:
arr2

array([[1, 2, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [86]:
arr1+arr2

array([[2, 3, 4],
       [2, 3, 2],
       [2, 3, 3]])

In [87]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  1,  0],
       [ 0, -1, -1]])

In [88]:
arr1*arr2 # index multiplication

array([[1, 2, 4],
       [1, 2, 1],
       [1, 2, 2]])

In [89]:
arr1@arr2

array([[4, 7, 7],
       [4, 6, 6],
       [3, 5, 5]])

In [90]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 2. , 1. ],
       [1. , 0.5, 0.5]])

In [91]:
arr1/0

C:\Users\thang\AppData\Local\Temp\ipykernel_20276\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [92]:
# Numpy Broadcasting

In [93]:
arr = np.zeros((3,4))

In [94]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [96]:
arr-5

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [97]:
a = np.array([1,2,3,4])

In [98]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [99]:
b = np.array([[3,4,5]])

In [100]:
arr1=arr+b.T

In [101]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [102]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [103]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [104]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [105]:
np.min(arr1)

3.0

In [106]:
np.max(arr1)

5.0

In [107]:
n = np.random.randint(1,10,(4,4))

In [108]:
n

array([[5, 3, 2, 1],
       [7, 5, 8, 8],
       [9, 3, 2, 3],
       [2, 2, 4, 3]])

In [109]:
n.reshape(8,2)

array([[5, 3],
       [2, 1],
       [7, 5],
       [8, 8],
       [9, 3],
       [2, 3],
       [2, 2],
       [4, 3]])

In [110]:
n.T

array([[5, 7, 9, 2],
       [3, 5, 3, 2],
       [2, 8, 2, 4],
       [1, 8, 3, 3]])

In [111]:
n.flatten()

array([5, 3, 2, 1, 7, 5, 8, 8, 9, 3, 2, 3, 2, 2, 4, 3])

In [112]:
np.expand_dims(n)

TypeError: expand_dims() missing 1 required positional argument: 'axis'

In [113]:
np.expand_dims(n,axis=1)

array([[[5, 3, 2, 1]],

       [[7, 5, 8, 8]],

       [[9, 3, 2, 3]],

       [[2, 2, 4, 3]]])

In [114]:
np.expand_dims(n,axis=0)

array([[[5, 3, 2, 1],
        [7, 5, 8, 8],
        [9, 3, 2, 3],
        [2, 2, 4, 3]]])

In [115]:
data = np.array([[1],[2],[3]])

In [116]:
data

array([[1],
       [2],
       [3]])

In [117]:
np.squeeze(data)

array([1, 2, 3])

In [118]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [119]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [120]:
np.roll(data,2)  

array([[2],
       [3],
       [1]])

In [121]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [122]:
arr1= np.random.randint(1,10,(3,4))
arr2= np.random.randint(1,10,(3,4))

In [123]:
arr1

array([[5, 7, 5, 8],
       [6, 5, 1, 1],
       [4, 5, 1, 8]])

In [124]:
arr2

array([[9, 2, 5, 7],
       [9, 2, 1, 4],
       [2, 9, 4, 4]])

In [125]:
arr1+arr2

array([[14,  9, 10, 15],
       [15,  7,  2,  5],
       [ 6, 14,  5, 12]])

In [126]:
arr1*arr2

array([[45, 14, 25, 56],
       [54, 10,  1,  4],
       [ 8, 45,  4, 32]])

In [127]:
arr1/arr2

array([[0.55555556, 3.5       , 1.        , 1.14285714],
       [0.66666667, 2.5       , 1.        , 0.25      ],
       [2.        , 0.55555556, 0.25      , 2.        ]])

In [128]:
arr1-arr2

array([[-4,  5,  0,  1],
       [-3,  3,  0, -3],
       [ 2, -4, -3,  4]])

In [129]:
arr1**arr2

array([[ 1953125,       49,     3125,  2097152],
       [10077696,       25,        1,        1],
       [      16,  1953125,        1,     4096]])

In [130]:
~arr1

array([[-6, -8, -6, -9],
       [-7, -6, -2, -2],
       [-5, -6, -2, -9]])

In [131]:
arr1>arr2

array([[False,  True, False,  True],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [132]:
arr=np.array(["praddep","Kumar"])

In [133]:
np.char.upper(arr)

array(['PRADDEP', 'KUMAR'], dtype='<U7')

In [134]:
np.char.capitalize(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [135]:
np.char.title(arr)

array(['Praddep', 'Kumar'], dtype='<U7')

In [136]:
arr1

array([[5, 7, 5, 8],
       [6, 5, 1, 1],
       [4, 5, 1, 8]])

In [137]:
np.sin(arr1)

array([[-0.95892427,  0.6569866 , -0.95892427,  0.98935825],
       [-0.2794155 , -0.95892427,  0.84147098,  0.84147098],
       [-0.7568025 , -0.95892427,  0.84147098,  0.98935825]])

In [138]:
np.cos(arr1)

array([[ 0.28366219,  0.75390225,  0.28366219, -0.14550003],
       [ 0.96017029,  0.28366219,  0.54030231,  0.54030231],
       [-0.65364362,  0.28366219,  0.54030231, -0.14550003]])

In [139]:
np.tan(arr1)

array([[-3.38051501,  0.87144798, -3.38051501, -6.79971146],
       [-0.29100619, -3.38051501,  1.55740772,  1.55740772],
       [ 1.15782128, -3.38051501,  1.55740772, -6.79971146]])

In [140]:
np.log10(arr1)

array([[0.69897   , 0.84509804, 0.69897   , 0.90308999],
       [0.77815125, 0.69897   , 0.        , 0.        ],
       [0.60205999, 0.69897   , 0.        , 0.90308999]])

In [141]:
np.exp(arr1)

array([[1.48413159e+02, 1.09663316e+03, 1.48413159e+02, 2.98095799e+03],
       [4.03428793e+02, 1.48413159e+02, 2.71828183e+00, 2.71828183e+00],
       [5.45981500e+01, 1.48413159e+02, 2.71828183e+00, 2.98095799e+03]])

In [142]:
np.power(arr1,2)

array([[25, 49, 25, 64],
       [36, 25,  1,  1],
       [16, 25,  1, 64]], dtype=int32)

In [143]:
np.mean(arr1)

4.666666666666667

In [144]:
np.median(arr1)

5.0

In [145]:
np.std(arr1)

2.4267032964268394

In [146]:
np.var(arr1)

5.888888888888889

In [147]:
np.min(arr1)

1

In [148]:
np.max(arr1)

8

In [149]:
arr1

array([[5, 7, 5, 8],
       [6, 5, 1, 1],
       [4, 5, 1, 8]])

In [150]:
arr2

array([[9, 2, 5, 7],
       [9, 2, 1, 4],
       [2, 9, 4, 4]])

In [151]:
arr1-arr2

array([[-4,  5,  0,  1],
       [-3,  3,  0, -3],
       [ 2, -4, -3,  4]])

In [152]:
np.subtract(arr1,arr2)

array([[-4,  5,  0,  1],
       [-3,  3,  0, -3],
       [ 2, -4, -3,  4]])

In [153]:
np.multiply(arr1,arr2)

array([[45, 14, 25, 56],
       [54, 10,  1,  4],
       [ 8, 45,  4, 32]])

In [154]:
np.mod(arr1,arr2)

array([[5, 1, 0, 1],
       [6, 1, 0, 1],
       [0, 5, 1, 0]])

In [155]:
np.power(arr1,arr2)

array([[ 1953125,       49,     3125,  2097152],
       [10077696,       25,        1,        1],
       [      16,  1953125,        1,     4096]])

In [156]:
np.sqrt(arr1)

array([[2.23606798, 2.64575131, 2.23606798, 2.82842712],
       [2.44948974, 2.23606798, 1.        , 1.        ],
       [2.        , 2.23606798, 1.        , 2.82842712]])

In [157]:
np.mean(arr1)

4.666666666666667

In [158]:
np.median(arr1)

5.0

In [159]:
np.std(arr1)

2.4267032964268394

In [160]:
np.var(arr1)

5.888888888888889

In [161]:
a=np.array([20,3,40,5,6])

In [162]:
np.sort(a)

array([ 3,  5,  6, 20, 40])

In [163]:
np.searchsorted(a,6)

2

In [164]:
np.searchsorted(a,60)

5

In [165]:
arr1=np.array([0,2,6,4,8888,8654641,1,0])

In [166]:
np.count_nonzero(arr1)

6

In [167]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

In [168]:
np.extract(arr1>50,arr1)

array([   8888, 8654641])

In [169]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [170]:
arr.byteswap()

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [171]:
arr

array(['praddep', 'Kumar'], dtype='<U7')

In [172]:
arr.byteswap(True)

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [173]:
a

array([20,  3, 40,  5,  6])

In [174]:
d=np.copy(a)

In [175]:
d

array([20,  3, 40,  5,  6])

In [176]:
d = arr.view()

In [177]:
d

array(['\U70000000\U72000000\U61000000\U64000000\U64000000\U65000000\U70000000',
       '\U4b000000\U75000000\U6d000000\U61000000\U72000000'], dtype='<U7')

In [178]:
d[0]=234

In [179]:
d

array(['234', '\U4b000000\U75000000\U6d000000\U61000000\U72000000'],
      dtype='<U7')

In [180]:
arr

array(['234', '\U4b000000\U75000000\U6d000000\U61000000\U72000000'],
      dtype='<U7')

In [181]:
import numpy.matlib as nm

In [182]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [183]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [184]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [185]:
# Linear Algebra

In [186]:
arr1

array([      0,       2,       6,       4,    8888, 8654641,       1,
             0])

In [187]:
arr1=np.random.randint([[2,3],[4,5]])

In [188]:
arr2=np.random.randint([[5,3],[2,5]])

In [189]:
arr1

array([[1, 0],
       [2, 0]])

In [190]:
arr2

array([[0, 1],
       [0, 1]])

In [191]:
np.dot(arr1,arr2)

array([[0, 1],
       [0, 2]])

In [192]:
arr1@arr2

array([[0, 1],
       [0, 2]])

In [193]:
a = np.array([1,2,3])

In [ ]:
54321
5432
543
54
5

In [199]:
for i in range(5,0,-1):
    for j in range(5,5-i,-1):
        print(j,end='')
    print()

54321
5432
543
54
5


In [ ]:
Now for the same list give me the frequencies along with unique values.
['1','6','9','3','0','12','11','7','6','11','0','11']

{'1':1, '11':3...}
Sorted by Key.

Also find the "Alphabet" quivalent for each of these numbers considering 
0 as A
25 as Z

In [200]:
# create a fibonacci series.
def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]
    else:
        fib_series = fibonacci(n - 1)
        fib_series.append(fib_series[-1] + fib_series[-2])
        return fib_series

n = int(input("Enter the number of Fibonacci numbers to generate: "))
fib_series = fibonacci(n)
print(f"Fibonacci series of length {n}:")
print(fib_series)


Enter the number of Fibonacci numbers to generate: 5
Fibonacci series of length 5:
[0, 1, 1, 2, 3]


In [201]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Print the unique values and their frequencies
print("Unique Values:", unique_values)
print("Frequencies:", frequencies)


Unique Values: ['1', '6', '9', '3', '0', '12', '11', '7']
Frequencies: [1, 2, 1, 1, 2, 1, 3, 1]


In [202]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Create a dictionary with unique values as keys and frequencies as values
result_dict = {unique_values[i]: frequencies[i] for i in range(len(unique_values))}

# Sort the dictionary by key in ascending order
sorted_result = dict(sorted(result_dict.items()))

# Print the sorted dictionary
print(sorted_result)


{'0': 2, '1': 1, '11': 3, '12': 1, '3': 1, '6': 2, '7': 1, '9': 1}


In [203]:
from collections import Counter

data = ['1', '6', '9', '3', '0', '12', '11', '7', '6', '11', '0', '11']

# Use Counter to count the frequency of each element
frequency_counter = Counter(data)

# Get the unique values and their frequencies
unique_values = list(frequency_counter.keys())
frequencies = list(frequency_counter.values())

# Create a dictionary with unique values as keys and frequencies as values
result_dict = {unique_values[i]: frequencies[i] for i in range(len(unique_values))}

# Sort the dictionary by key in ascending order
sorted_result = dict(sorted(result_dict.items()))

# Define a function to convert numbers to alphabets
def num_to_alphabet(num):
    return chr(ord('A') + int(num))

# Convert the keys to alphabets in the sorted dictionary
alphabet_equivalent = {num_to_alphabet(k): v for k, v in sorted_result.items()}

# Print the sorted dictionary with alphabet equivalents
print(alphabet_equivalent)


{'A': 2, 'B': 1, 'L': 3, 'M': 1, 'D': 1, 'G': 2, 'H': 1, 'J': 1}
